// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCieEFDMt9QbdVf4tl23IWieOSh86ers',
    appId: '1:1081452186768:web:7b9b391cb230d46cd0dc15',
    messagingSenderId: '1081452186768',
    projectId: 'lcaapp-7d817',
    authDomain: 'lcaapp-7d817.firebaseapp.com',
    storageBucket: 'lcaapp-7d817.appspot.com',
    measurementId: 'G-CJKMCT2VM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD191rTTztXBHqeRmprLMK7sbWlB2kMDU0',
    appId: '1:1081452186768:android:97c41ae508ef60f8d0dc15',
    messagingSenderId: '1081452186768',
    projectId: 'lcaapp-7d817',
    storageBucket: 'lcaapp-7d817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaLk-7DVdBwKUdazC2pukgGpgrvYPViDk',
    appId: '1:1081452186768:ios:4156f2773ad5e72bd0dc15',
    messagingSenderId: '1081452186768',
    projectId: 'lcaapp-7d817',
    storageBucket: 'lcaapp-7d817.appspot.com',
    iosBundleId: 'com.lca.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaLk-7DVdBwKUdazC2pukgGpgrvYPViDk',
    appId: '1:1081452186768:ios:7ce19b60e43492bed0dc15',
    messagingSenderId: '1081452186768',
    projectId: 'lcaapp-7d817',
    storageBucket: 'lcaapp-7d817.appspot.com',
    iosBundleId: 'com.example.lca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHCieEFDMt9QbdVf4tl23IWieOSh86ers',
    appId: '1:1081452186768:web:2e03f351ee336c84d0dc15',
    messagingSenderId: '1081452186768',
    projectId: 'lcaapp-7d817',
    authDomain: 'lcaapp-7d817.firebaseapp.com',
    storageBucket: 'lcaapp-7d817.appspot.com',
    measurementId: 'G-VP2RW8BT1S',
  );

}