import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'User Registration': 'User Registration',
          'Name*': ' Name',
          'Phone Number*': 'Phone Number',
          'Email ID*': 'Email ID',
          'Password*': 'Password',
          'Confirm Password*': 'Confirm Password',
          'Agree to Terms and Conditions': 'Agree to Terms and Conditions',
          'Register': 'Register',
          'Auto Detect GPS': 'Auto Detect GPS',
          'Country*': 'Country',
          'State*': 'State',
          'Pincode*': 'Pincode',
          'City*': 'City',
          "Create": "Create",
          'Full Address': 'Full Address',
          "Don't have an Account?": "Don't have an Account?",
          'Almost there!': 'Almost there!',
          'We have sent you an OTP\non number XXXXXX0000':
              'We have sent you an OTP\non number XXXXXX0000',
          'One time Password': 'One time Password',
          'Didnt receive OTP?': 'Didnt receive OTP?',
          'Resend SMS': 'Resend SMS',
          "Verify OTP": 'Verify OTP',
          'LOGIN': 'LOGIN',
          "Don't have a Account": "Don't have a Account",
          'via Email': 'via Email',
          'via Phone': 'via Phone',
          'Send OTP': 'Send OTP',
          "Already have an account?": "Already have an account?",
          'OTP': 'OTP',
          'Login': 'Login',
          'Register Device': 'Register Device',
          'Device Details': "Device Details",
          'Device IMEI': 'Device IMEI',
          'Device ID': "Device ID",
          'Device Name': 'Device Name',
          'GPS Location': 'GPS Location',
          "Current Location": "Current Location",
          'Supported Protocol': 'Supported Protocol',
          'MQTT': 'MQTT',
          'Submit': "Submit",
          "My Complaints": "My Complaints",
          "Complaint": "Complaint",
          "Having Issues?\n": "Having Issues?\n",
          "Don’t Worry,We got you!": "Don’t Worry,We got you!",
          "Register Complaint": "Register Complaint",
          "View Complaints": "View Complaints",
          "For further Assistance \nContact us at +910101010 ":
              "For further Assistance \nContact us at +910101010 ",
          "Please fill the form below to register you complaint.":
              "Please fill the form below to register you complaint.",
          "Problem": "Problem",
          "Issue 1": "Issue 1",
          "Describe your problem...": "Describe your problem...",
          "HOME": "HOME",
          "SEARCH": "SEARCH",
          "MAP": "MAP",
          "PROFILE": "PROFILE",
          "* Required Fields": "Required Fields",
          "My Devices": "My Devices",
          "Add Device": "Add Device",
          "Name": "Name",
          "Created On": "Created On",
          "Dashboard": "Dashboard",
          "Schedules": "Schedules",
          "< Back": "< Back",
          "Reload": "Reload",
          "Additional Information....": "Additional Information....",
          "Next": "Next",
          'Add Note': "Add Note",
          "Select IMEI": "Select IMEI",
          "Select Device Title": "Select Device Title",
          "Select Issue": "Select Issue",
          "Please Fill Out The Form To Register Your Complaint":
              "Please Fill Out The Form To Register Your Complaint",
          "Note": "Note",
          "SUBMIT": "SUBMIT",
          "EDIT": "EDIT",
          'Are all the details correct?': "Are all the details correct?",
          "Click Submit to confirm.": 'Click Submit to confirm.',
          "Complaint Details": "Complaint Details",
          "Compliant": "Compliant",
          "Programming": "Programming",
          'Logout': "Logout",
          "Edit Profile": "Edit Profile",
          "User Name": "User Name",
          "Save": "Save",
          "Change Password": "Change Password",
          "Pending": "Pending",
          "Ticket No": "Ticket No",
          "Date": "Date",
          "Status": "Status",
          "Expansion Mode": "Expansion Mode",
          "Address": "Address",
          "Total valve Count": "Total valve Count",
          "Connected": "Connected",
          "Not Connected": "Not Connected",
          "Device ID*": "Device ID*",
          "Device Name*": "Device Name*",
          "DASHBOARD": "DASHBOARD",
          "Settings": "Settings",
          'Delete Device': 'Delete Device',
          "Update Device": "Update Device",
          "Cancel": "Cancel",
          "Program A": "Program A",
          "Program B": "Program B",
          "View": "View",
          "SET": "SET"
        },
        'hi_IN': {
          'User Registration': 'उपयोगकर्ता पंजीकरण',
          'Name*': 'नाम',
          'Phone Number*': 'फ़ोन नंबर',
          'Email ID*': 'ईमेल ID',
          'Password*': 'पासवर्ड',
          'Confirm Password*': 'पासवर्ड पुष्टि करे',
          'Agree to Terms and Conditions': 'नियम एवं शर्तों से सहमत हैं',
          'Register': 'पंजीकृत करे',
          'Country*': 'देश',
          'State*': 'राज्य',
          'Auto Detect GPS': 'ऑटो डिटेक्ट जीपीएस',
          'Pincode*': 'पिन कोड',
          'City*': 'शहर/गांव',
          'Full Address': 'पूरा पता',
          'Almost there!': 'लगभग हो गया!',
          'Current Location': "वर्तमान स्थान",
          'We have sent you an OTP\non number XXXXXX0000':
              'हमने आपको एक OTP भेजा है नंबर XXXXXX0000 पर',
          'One time Password': 'एक बारी पासवर्ड',
          "Don't have an Account?": "कोई खाता नहीं है?",
          'Didnt receive OTP?': 'ओटीपी प्राप्त नहीं हुआ?',
          'Resend SMS': 'एसएमएस पुनः भेजें',
          'Verify OTP': "ओटीपी प्रमाणित करें",
          'LOGIN': 'लॉग इन करें',
          'via Email': 'ईमेल द्वारा',
          "Already have an Account?": "पहले से खाता है?",
          'via Phone': 'फ़ोन द्वारा',
          'Send OTP': 'OTP भेजें',
          'OTP': 'ओ.टी.पी',
          'Login': 'लॉग इन करें',
          'Register Device': 'डिवाइस पंजीकृत करें',
          'Device Details': 'डिवाइस विवरण',
          'Device IMEI': 'डिवाइस IMEI',
          'Device ID': 'डिवाइस आईडी',
          'Device Name': 'डिवाइस का नाम',
          'GPS Location': 'जीपीएस स्थान',
          'Supported Protocol': "समर्थित प्रोटोकॉल",
          'MQTT': 'एमक्यूटीटी',
          "* Required Fields": "*अनिवार्य फ़ील्ड्",
          "Agree to terms and conditions": "मैं नियम एवं शर्तों से सहमत हूँ",
          'Submit': 'जमा करना',
          "My Complaints": 'मेरी शिकायतें',
          "Create": "बनाएं",
          "Complaint": 'शिकायत',
          "Having Issues?\n": 'समस्याएँ आ रही हैं?',
          "Change Password": "पासवर्ड बदलें",
          "Don’t Worry,We got you!": ' चिंता मत करो, हमने तुम्हें पा लिया है!',
          "Register Complaint": 'शिकायत दर्ज करें',
          "View Complaints": 'शिकायतें देखें',
          "For further Assistance \nContact us at +910101010 ":
              'अधिक सहायता के लिए +910101010 पर हमसे संपर्क करें ',
          "Please fill the form below to register you complaint.":
              'कृपया अपनी शिकायत दर्ज करने के लिए नीचे दिया गया फॉर्म भरें। सभी आवश्यक विवरण जोड़ें',
          "Problem": 'अपनी समस्या बताएं...',
          "Issue 1": 'अंक 1',
          "Describe your problem...": 'अपनी समस्या बताएं...',
          "HOME": 'घर',
          "SEARCH": 'खोज',
          "MAP": 'नक्शा',
          "PROFILE": 'प्रोफ़ाइल',
          "My Devices": "मेरे उपकरण",
          "Add Device": "डिवाइस जोडे",
          "Name": "नाम",
          "Created On": "समय बनाया गया",
          "Dashboard": "डैशबोर्ड",
          "Schedules": "अनुसूचियों",
          "< Back": "<वापस",
          "Reload": 'पुनः लोड करें',
          "Next": 'अगला',
          "Additional Information....": "अतिरिक्त जानकारी....",
          "Add Note": "नोट जोड़े",
          "Select IMEI": "IMEI चुनें",
          "Select Device Title": "डिवाइस शीर्षक चुनें",
          "Select Issue": "अंतर्राष्ट्रीय शीर्षक चुनें",
          'Please Fill Out The Form To Register Your Complaint':
              "कृपया अपनी शिकायत दर्ज करने के लिए फॉर्म भरें",
          "Note": "टिप्पणी",
          "SUBMIT": "जमा करना",
          "EDIT": "संपादन करना",
          "Are all the details correct?": "क्या सभी विवरण सही हैं?",
          "Click Submit to confirm.": "पुष्टि करने के लिए सबमिट पर क्लिक करें।",
          "Complaint Details": "शिकायत विवरण",
          "Compliant": "शिकायत",
          "Programming": 'प्रोग्रामिंग',
          "Logout": "लॉग आउट",
          "Edit Profile": "प्रोफ़ाइल एडिट",
          "User Name": "उपयोगकर्ता नाम",
          "Save": "सेव",
          "Ticket No": "टिकट नं",
          "Date": "तारीख",
          "Status": "स्थिति",
          "Expansion Mode": "विस्तार मोड",
          "Total valve Count": "कुल वाल्व गणना",
          "Address": "पता",
          "Connected": "जुड़े हुए",
          "Not Connected": "जुड़े नहीं हैं",
          "Device ID*": "डिवाइस आईडी*",
          "Device Name*": "डिवाइस का नाम*",
          "DASHBOARD": "डैशबोर्ड",
          "Settings": " सेटिंग",
          'Delete Device': 'डिवाइस हटाएं',
          "Update Device": "डिवाइस अपडेट करें",
          "Cancel": "रद्द करें",
          "Program A": "प्रोग्राम ए",
          "Program B": "प्रोग्राम बी",
          "View": "व्यू",
          "SET": "सेट"
        },
      };
}
