import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'User Registration': 'User Registration',
          'Name*': ' Name',
          'Phone Number*': 'Phone Number',
          'Email ID*': 'Email ID',
          'Password*': 'Password',
          'Confirm Password*': 'Confirm Password',
          'Agree to Terms and Conditions': 'Agree to Terms and Conditions',
          'Register': 'Register',
          'Auto Detect GPS': 'Auto Detect GPS',
          'Country*': 'Country',
          'State*': 'State',
          'Pincode*': 'Pincode',
          'City*': 'City',
          "Create": "Create",
          'Full Address': 'Full Address',
          "Don't have an Account?": "Don't have an Account?",
          'Almost there!': 'Almost there!',
          'We have sent you an OTP\non number XXXXXX0000':
              'We have sent you an OTP\non number XXXXXX0000',
          'One time Password': 'One time Password',
          'Didnt receive OTP?': 'Didnt receive OTP?',
          'Resend SMS': 'Resend SMS',
          "Verify OTP": 'Verify OTP',
          'LOGIN': 'LOGIN',
          "Don't have a Account": "Don't have a Account",
          'via Email': 'via Email',
          'via Phone': 'via Phone',
          'Send OTP': 'Send OTP',
          "Already have an account?": "Already have an account?",
          'OTP': 'OTP',
          'Login': 'Login',
          'Register Device': 'Register Device',
          'Device Details': "Device Details",
          'Device IMEI': 'Device IMEI',
          'Device ID': "Device ID",
          'Device Name': 'Device Name',
          'GPS Location': 'GPS Location',
          "Current Location": "Current Location",
          'Supported Protocol': 'Supported Protocol',
          'MQTT': 'MQTT',
          'Submit': "Submit",
          "My Complaints": "My Complaints",
          "Complaint": "Complaint",
          "Fertilization": "Fertilization",
          "Having Issues?": "Having Issues?",
          "\nDon’t Worry,We got you!": "\nDon’t Worry,We got you!",
          "Register Complaint": "Register Complaint",
          "View Complaints": "View Complaints",
          "For further Assistance \nContact us at +910101010 ":
              "For further Assistance \nContact us at +910101010 ",
          "Please fill the form below to register you complaint.":
              "Please fill the form below to register your complaint.",
          "Problem": "Problem",
          "Issue 1": "Issue 1",
          "Describe your problem...": "Describe your problem...",
          "HOME": "HOME",
          "SEARCH": "SEARCH",
          "MAP": "MAP",
          "PROFILE": "PROFILE",
          "* Required Fields": "Required Fields",
          "My Devices": "Devices",
          "Add Device": "Add Device",
          "Name": "Name",
          "Created On": "Created On",
          "Dashboard": "Dashboard",
          "Schedules": "Schedules",
          "< Back": "< Back",
          "Reload": "Reload",
          "Additional Information....": "Additional Information....",
          "Next": "Next",
          'Add Note': "Add Note",
          "Select IMEI": "Select IMEI",
          "Select Device Title": "Select Device Title",
          "Select Issue": "Select Issue",
          "Please Fill Out The Form To Register Your Complaint":
              "Please Fill Out The Form To Register Your Complaint",
          "Note": "Note",
          "SUBMIT": "SUBMIT",
          "EDIT": "EDIT",
          'Are all the details correct?': "Are all the details correct?",
          "Click Submit to confirm.": 'Click Submit to confirm.',
          "Complaint Details": "Complaint Details",
          "Compliant": "Compliant",
          "Programming": "Programming",
          'Logout': "Logout",
          "Edit Profile": "Edit Profile",
          "User Name": "User Name",
          "Save": "Save",
          "Change Password": "Change Password",
          "Pending": "Pending",
          "Ticket No": "Ticket No",
          "Date": "Date",
          "Status": "Status",
          "Expansion Mode": "Expansion Mode",
          "Address": "Address",
          "Total valve Count": "Total valve Count",
          "Connected": "Connected",
          "Not Connected": "Not Connected",
          "Device ID*": "Device ID*",
          "Device Name*": "Device Name*",
          "DASHBOARD": "DASHBOARD",
          "Settings": "Settings",
          'Delete Device': 'Delete Device',
          "Update Device": "Update Device",
          "Cancel": "Cancel",
          "Program A": "Program A",
          "Program B": "Program B",
          "View": "View",
          "SET": "SET",
          "Program": "Program",
          'Action': 'Action',
          "My Programs": "Programs",
          'Configure': 'Configure',
          "Create Program": "Create Program",
          "Please Select the program and mode to create schedule":
              "Please select the program and mode to create schedule",
          "Select Days": 'Select Days',
          'Reset All': 'Reset All',
          "to follow the schedule": "to follow the schedule",
          "Mode": "Mode",
          'Monday': 'Monday',
          'Tuesday': 'Tuesday',
          'Wednesday': 'Wednesday',
          'Thrusday': 'Thrusday',
          'Friday': 'Friday',
          'Saturday': 'Saturday',
          'Sunday': 'Sunday',
          "Irrigation": "Irrigation",
          "Fertigation": "Fertigation",
          "Start Time: ": "Start Time: ",
          "Valve Duration  : ": "Valve Duration  : ",
          "End Time  : ": "End Time  : ",
          "Start Time 2 : ": "Start Time 2 : ",
          'Time exceeds 24 hours': 'Time exceeds 24 hours',
          'Confirm': 'Confirm',
          "Start from today?": "Start from today?",
          'Pump initial time': 'Pump initial time',
          'Pump recharge time': 'Pump recharge time',
          "Days": "Days",
          "Power On": "Power On",
          "Power off": "Power off",
          'No Rain': 'No Rain',
          'Raining': 'Raining',
          'Low Flow': 'Low Flow',
          "Please fill the form below to register your device":
              "Please fill the form below to register your device",
          "Please fill the form below to edit you device":
              "Please fill the form below to edit your device",
          "Please fill the form below to edit you device.\nAdd all the required details":
              "Please fill the form below to edit your device.\nAdd all the required details",
          "Didn't receive OTP?": "Didn't receive OTP?",
          "Total Time for valves is": "Total Time for valves is",
          'Prewet': 'Prewet',
          'Fertilize': 'Fertilize',
          'Flush': 'Flush',
          'Total': 'Total',
          'This expansion count will reflect on next schedule save':
              'This expansion count will reflect on next schedule save'
        },
        'hi_IN': {
          'User Registration': 'उपभोक्ता पंजीकरण',
          'Name*': 'नाम',
          'Phone Number*': 'फ़ोन नंबर',
          'Email ID*': 'ईमेल ID',
          'Password*': 'पासवर्ड',
          'Confirm Password*': 'पासवर्ड पुष्टि करे',
          'Agree to Terms and Conditions': 'मैं नियम एवं शर्तों से सहमत हूँ',
          'Register': 'पंजीकरण करें',
          'Country*': 'देश',
          'State*': 'राज्य',
          'Auto Detect GPS': 'ऑटो डिटेक्ट GPS',
          'Pincode*': 'पिन कोड',
          'City*': 'शहर/गांव', //  city/village
          'Full Address': 'पूरा पता',
          'Almost there!': 'कुछ देर और!',
          'Current Location': "वर्तमान स्थान",
          'We have sent you an OTP\non number XXXXXX0000':
              'आपके मोबाइल  XXXXXX0000  नंबर पर एक ओटीपी भेजा गया है',
          'One time Password': 'एक बार पासवर्ड दर्ज करें',
          "Don't have an Account?": "कोई खाता नहीं है?",
          'Didnt receive OTP?': 'OTP प्राप्त नहीं हुआ?',
          'Resend SMS': 'SMS पुनः भेजें',
          'Verify OTP': "OTP प्रमाणित करें",
          'LOGIN': 'लॉगिन करें',
          'via Email': 'ईमेल द्वारा',
          "Already have an Account?": "पहले से खाता है?",
          'via Phone': 'फ़ोन द्वारा',
          'Send OTP': 'OTP भेजें',
          'OTP': 'O.T.P',
          "Didn't receive OTP?": "OTP नहीं मिला",
          'Login': 'लॉगिन करें',
          'Register Device': 'डिवाइस पंजीकृत करें',
          'Device Details': 'डिवाइस सूचना',
          'Device IMEI': 'डिवाइस IMEI',
          'Device ID': 'डिवाइस ID',
          'Device Name': 'डिवाइस का नाम',
          'GPS Location': 'GPS स्थान',
          'Supported Protocol': "कार्यरत प्रोटोकॉल",
          'MQTT': 'MQTT',
          "* Required Fields": "*अनिवार्य ",
          "Agree to terms and conditions": "मैं नियम एवं शर्तों से सहमत हूँ", //
          'Submit': 'भेजें ',
          "My Complaints": 'मेरी समस्याएं',
          "Create": "दर्ज करें ",
          "Complaint": 'समस्या',
          "Having Issues?": 'समस्या हो रही है?',
          "Change Password": "पासवर्ड बदलें",
          "\nDon’t Worry,We got you!": '\nआपके लिए हम हैं,चिंता ना करें!',
          "Register Complaint": 'शिकायत दर्ज करें',
          "View Complaints": 'शिकायतों को देखें ',
          "For further Assistance \nContact us at +910101010 ":
              'अधिक सहायता के लिए संपर्क करें: +910101010 ',
          "Please fill the form below to register you complaint.":
              'कृपया अपनी शिकायत दर्ज करने के लिए नीचे दिए गए फॉर्म को भरें।',
          "Problem": 'समस्या',
          "Issue 1": 'समस्या 1',
          "Describe your problem...": 'अपनी समस्या बताएं...',
          "HOME": 'होम',
          "SEARCH": 'खोजना',
          "MAP": 'नक्शा',
          "PROFILE": 'प्रोफ़ाइल',
          "My Devices": "डिवाइस",
          "Add Device": "डिवाइस जोडे",
          "Name": "नाम",
          "Created On": "जोड़ने की तारीख",
          "Dashboard": "डैशबोर्ड",
          "Schedules": "प्रोग्राम", // schedules to program
          "< Back": "<वापस",
          "Reload": 'पुनः लोड करें',
          "Next": 'आगामी',
          "Additional Information....": "अतिरिक्त जानकारी....",
          "Add Note": "टिप्पणी",
          "Select IMEI": "IMEI चुनें",
          "Select Device Title": "डिवाइस शीर्षक चुनें",
          "Select Issue": " समस्या चुनें",
          'Please Fill Out The Form To Register Your Complaint':
              "कृपया अपनी शिकायत दर्ज करने के लिए नीचे दिए गए फॉर्म को भरें।",
          "Total Time for valves is": "सभी वाल्व चलने की कुल अवधि",
          "Note": "टिप्पणी",
          "SUBMIT": "सेव करें ",
          "EDIT": "संपादन",
          "Are all the details correct?": "क्या सभी सूचना सही हैं?",
          "Click Submit to confirm.": "पुष्टि करने के लिए सबमिट पर क्लिक करें।",
          "Complaint Details": "शिकायत विवरण",
          "Compliant": "समस्या",
          "Programming": 'प्रोग्रामिंग',
          "Logout": "लॉग आउट",
          "Edit Profile": "प्रोफ़ाइल एडिट",
          "User Name": "उपभोक्ता का नाम",
          "Save": "सेव",
          "Ticket No": "टिकट नं",
          "Date": "तारीख",
          "Status": "स्थिति",
          "Expansion Mode": "विस्तार मोड",
          "Total valve Count": "कुल वाल्व गणना",
          "Address": "पता",
          "Connected": "जुड़े हैं",
          "Not Connected": "जुड़े नहीं हैं",
          "Device ID*": "डिवाइस ID*",
          "Device Name*": "डिवाइस का नाम*",
          "DASHBOARD": "डैशबोर्ड",
          "Settings": " सेटिंग",
          'Delete Device': 'डिवाइस हटाएं',
          "Update Device": "डिवाइस अपडेट करें",
          "Cancel": "रद्द करें",
          "Program A": "प्रोग्राम ए",
          "Program B": "प्रोग्राम बी",
          "View": "देखें",
          "SET": "सेट",
          "NOT SET": "सेट नहीं ",
          "Program": "प्रोग्राम",
          'Action': 'प्रक्रिया',
          "My Programs": "प्रोग्राम",
          'Configure': 'प्रोग्राम स्थापित करें',
          "Create Program": "प्रोग्राम बनाएं",
          'Please Select the program and mode to create schedule':
              "कृपया शेड्यूल बनाने के लिए प्रोग्राम और मोड का चयन करें",
          "Select Days": "दिन चुनें",
          "Days": "दिन",
          'Reset All': 'रिसेट ऑल',
          "to follow the schedule":
              "प्रोग्राम का पालन करने के लिए", // schedule to program
          "Mode": "मोड",
          'Monday': 'सोमवार',
          'Tuesday': 'मंगलवार',
          'Wednesday': 'बुधवार',
          'Thrusday': 'गुरुवार',
          'Friday': 'शुक्रवार',
          'Saturday': 'शनिवार',
          'Sunday': 'रविवार',
          "Irrigation": "सिंचाई",
          "Fertigation": "फर्टिगेशन",
          "Fertilization": "फर्टिगेशन",
          "Start Time": "प्रारंभ समय",
          "Valve Duration  : ": "वाल्व अवधि:",
          "End Time": "समाप्ति समय",
          "Please fill the form below to register your device":
              "कृपया अपना डिवाइस रजिस्टर करने के लिए नीचे दिया गया फॉर्म भरें",
          'Time exceeds 24 hours': 'समय 24 घंटे से अधिक',
          'Confirm': 'पुष्टि',
          "Start from today?": "आज से शुरू करें?",
          'Pump initial time': 'पम्प प्रारंभ समय',
          'Pump recharge time': 'पम्प रिचार्ज समय',
          "Power On": "विधुत ON",
          "Power off": "विधुत OFF",
          'No Rain': 'साफ़ मौसम',
          'Raining': 'बारिश',
          'Low Flow': 'Low Flow',
          "Please fill the form below to edit you device.\nAdd all the required details":
              "कृपया अपने डिवाइस को संपादित करने के लिए नीचे दिया गया फॉर्म भरें।\nसभी आवश्यक विवरण जोड़ें",
          'Prewet': "प्रीवेट",
          'Fertilize': 'फर्टिगेशन',
          'Flush': 'फ्लशिंग',
          'Total': 'कुल समय',
          'This expansion count will reflect on next schedule save':
              'इस विस्तार की संख्या अगले शेड्यूल बचत पर दिखाई देगी।'
        },
        "mr_IN": {
          'User Registration': 'वापरकर्ता नोंदणी',
          'Name*': 'नाव',
          'Phone Number*': 'फोन नंबर',
          'Email ID*': 'ईमेल आयडी',
          'Password*': 'पासवर्ड',
          'Confirm Password*': 'पासवर्डची पुष्टी करा',
          'Agree to Terms and Conditions': 'अटी आणि शर्तींशी सहमती दर्शवा',
          'Register': 'नोंदणी करा',
          'Auto Detect GPS': 'स्वयंचलित GPS शोधा',
          'Country*': 'देश',
          'State*': 'राज्य',
          'Pincode*': 'पिनकोड',
          'City*': 'शहर',
          "Create": "निर्माण करा",
          'Full Address': 'संपूर्ण पत्ता',
          "Don't have an Account?": "खाते नाहीये?",
          'Almost there!': 'जवळजवळ झाले!',
          'We have sent you an OTP\non number XXXXXX0000':
              'आम्ही XXXXXX0000 या क्रमांकावर OTP पाठवला आहे',
          'One time Password': 'एकवेळ पासवर्ड',
          'Didnt receive OTP?': 'OTP मिळाला नाही?',
          'Resend SMS': 'SMS पुन्हा पाठवा',
          "Verify OTP": 'OTP सत्यापित करा',
          'LOGIN': 'लॉगिन',
          "Don't have a Account": "खाते नाहीये",
          'via Email': 'ईमेल द्वारे',
          'via Phone': 'फोन द्वारे',
          'Send OTP': 'OTP पाठवा',
          "Already have an account?": "आधीपासून खाते आहे?",
          'OTP': 'OTP',
          'Login': 'लॉगिन',
          'Register Device': 'डिव्हाइस नोंदणी',
          'Device Details': "डिव्हाइस तपशील",
          'Device IMEI': 'डिव्हाइस IMEI',
          'Device ID': "डिव्हाइस आयडी",
          'Device Name': 'डिव्हाइस नाव',
          'GPS Location': 'GPS स्थान',
          "Current Location": "सध्याचे स्थान",
          'Supported Protocol': 'समर्थित प्रोटोकॉल',
          'MQTT': 'MQTT',
          'Submit': "सबमिट",
          "My Complaints": "माझ्या तक्रारी",
          "Complaint": "तक्रार",
          "Having Issues?": "समस्या आहेत?",
          "\nDon’t Worry,We got you!":
              "\nकाळजी करू नका, आम्ही तुमच्यासाठी आहोत!",
          "Register Complaint": "तक्रार नोंदवा",
          "View Complaints": "तक्रारी पहा",
          "For further Assistance \nContact us at +910101010 ":
              "अधिक सहाय्यासाठी \n+910101010 वर आमच्याशी संपर्क साधा",
          "Please fill the form below to register you complaint.":
              "कृपया तुमची तक्रार नोंदवण्यासाठी खालील फॉर्म भरा.",
          "Problem": "समस्या",
          "Issue 1": "समस्या 1",
          "Describe your problem...": "तुमची समस्या वर्णन करा...",
          "HOME": "मुख्यपृष्ठ",
          "SEARCH": "शोधा",
          "MAP": "नकाशा",
          "PROFILE": "प्रोफाइल",
          "* Required Fields": "* आवश्यक फील्ड",
          "My Devices": "माझी डिव्हाइस",
          "Add Device": "डिव्हाइस जोडा",
          "Name": "नाव",
          "Created On": "निर्मितीची तारीख",
          "Dashboard": "डॅशबोर्ड",
          "Schedules": "वेळापत्रक",
          "< Back": "< मागे",
          "Reload": "रीलोड",
          "Additional Information....": "अधिक माहिती....",
          "Next": "पुढे",
          'Add Note': "नोट जोडा",
          "Select IMEI": "IMEI निवडा",
          "Select Device Title": "डिव्हाइस शीर्षक निवडा",
          "Select Issue": "समस्या निवडा",
          "Please Fill Out The Form To Register Your Complaint":
              "तुमची तक्रार नोंदवण्यासाठी कृपया फॉर्म भरा",
          "Note": "नोट",
          "SUBMIT": "सबमिट",
          "EDIT": "संपादित करा",
          'Are all the details correct?': "सर्व तपशील बरोबर आहेत का?",
          "Click Submit to confirm.": 'पुष्टीसाठी सबमिट क्लिक करा.',
          "Complaint Details": "तक्रार तपशील",
          "Compliant": "अनुरूप",
          "Programming": "प्रोग्रामिंग",
          'Logout': "बाहेर पडा",
          "Edit Profile": "प्रोफाइल संपादित करा",
          "User Name": "वापरकर्ता नाव",
          "Save": "जतन करा",
          "Change Password": "पासवर्ड बदला",
          "Pending": "प्रलंबित",
          "Ticket No": "तिकीट क्र.",
          "Date": "तारीख",
          "Status": "स्थिती",
          "Expansion Mode": "विस्तार मोड",
          "Address": "पत्ता",
          "Total valve Count": "एकूण वाल्वे संख्या",
          "Connected": "जोडलेले",
          "Not Connected": "जोडलेले नाहीत",
          "Device ID*": "डिव्हाइस आयडी*",
          "Device Name*": "डिव्हाइस नाव*",
          "DASHBOARD": "डॅशबोर्ड",
          "Settings": "सेटिंग्ज",
          'Delete Device': 'डिव्हाइस हटवा',
          "Update Device": "डिव्हाइस अद्यतनित करा",
          "Cancel": "रद्द करा",
          "Program A": "प्रोग्राम A",
          "Program B": "प्रोग्राम B",
          "View": "पहा",
          "SET": "सेट",
          "Program": "प्रोग्राम",
          'Action': 'क्रिया',
          "My Programs": "माझे प्रोग्राम",
          'Configure': 'कॉन्फिगर करा',
          "Create Program": "प्रोग्राम तयार करा",
          "Please Select the program and mode to create schedule":
              "वेळापत्रक तयार करण्यासाठी कृपया प्रोग्राम आणि मोड निवडा",
          "Select Days": 'दिवस निवडा',
          'Reset All': 'सर्व रीसेट करा',
          "to follow the schedule": "वेळापत्रकाचे पालन करण्यासाठी",
          "Mode": "मोड",
          'Monday': 'सोमवार',
          'Tuesday': 'मंगळवार',
          'Wednesday': 'बुधवार',
          'Thrusday': 'गुरुवार',
          'Friday': 'शुक्रवार',
          'Saturday': 'शनिवार',
          'Sunday': 'रविवार',
          "Irrigation": "सिंचन",
          "Fertigation": "खत टाकणे",
          "Start Time: ": "सुरुवातीचा वेळ: ",
          "Valve Duration  : ": "वाल्वे कालावधी  : ",
          "End Time  : ": "समाप्ती वेळ  : ",
          "Start Time 2 : ": "सुरुवातीचा वेळ 2 : ",
          'Time exceeds 24 hours': 'वेळ 24 तासांपेक्षा जास्त आहे',
          'Confirm': 'पुष्टी करा',
          "Start from today?": "आजपासून प्रारंभ?",
          'Pump initial time': 'पंप सुरू होण्याची वेळ',
          'Pump recharge time': 'पंप रिचार्ज वेळ',
          "Days": "दिवस",
          "Power On": "पॉवर ऑन",
          "Power off": "पॉवर ऑफ",
          'No Rain': 'पाऊस नाही',
          'Raining': 'पाऊस पडत आहे',
          'Low Flow': 'कमी प्रवाह',
          "Please fill the form below to edit you device.\nAdd all the required details":
              "तुमचे डिव्हाइस संपादित करण्यासाठी कृपया खालील फॉर्म भरा.\nसर्व आवश्यक तपशील भरा",
          "Total Time for valves is": "सभी वाल्व चलने की कुल अवधि"
        },
        "gu_IN": {
          'User Registration': 'વપરાશકર્તા નોંધણી',
          'Name*': 'નામ',
          'Phone Number*': 'ફોન નંબર',
          'Email ID*': 'ઇમેલ આઈડી',
          'Password*': 'પાસવર્ડ',
          'Confirm Password*': 'પાસવર્ડની પુષ્ટિ કરો',
          'Agree to Terms and Conditions': 'શરતો અને નિયમો સ્વીકારો',
          'Register': 'નોંધણી કરો',
          'Auto Detect GPS': 'ઓટો GPS શોધો',
          'Country*': 'દેશ',
          'State*': 'રાજ્ય',
          'Pincode*': 'પિનકોડ',
          'City*': 'શહેર',
          'Create': 'બનાવો',
          'Full Address': 'પૂર્ણ સરનામું',
          "Don't have an Account?": 'ખાતા નથી?',
          'Almost there!': 'લગભગ પહોંચી ગયા!',
          'We have sent you an OTP\non number XXXXXX0000':
              'અમે તમારાં નંબર XXXXXX0000 પર OTP મોકલ્યો છે',
          'One time Password': 'એક વારનો પાસવર્ડ',
          'Didnt receive OTP?': 'OTP મળી નથી?',
          'Resend SMS': 'SMS ફરીથી મોકલો',
          'Verify OTP': 'OTP તપાસો',
          'LOGIN': 'લૉગિન',
          "Don't have a Account": 'એકાઉન્ટ નથી?',
          'via Email': 'ઇમેલ દ્વારા',
          'via Phone': 'ફોન દ્વારા',
          'Send OTP': 'OTP મોકલો',
          "Already have an account?": 'પહેલેથી જ એકાઉન્ટ છે?',
          'OTP': 'OTP',
          'Login': 'લૉગિન',
          'Register Device': 'ડિવાઈસ રજીસ્ટર કરો',
          'Device Details': 'ડિવાઈસ વિગતો',
          'Device IMEI': 'ડિવાઈસ IMEI',
          'Device ID': 'ડિવાઈસ ID',
          'Device Name': 'ડિવાઈસનું નામ',
          'GPS Location': 'GPS સ્થાન',
          'Current Location': 'વર્તમાન સ્થાન',
          'Supported Protocol': 'સમર્થિત પ્રોટોકોલ',
          'MQTT': 'MQTT',
          'Submit': 'સબમિટ કરો',
          'My Complaints': 'મારી ફરિયાદો',
          'Complaint': 'ફરિયાદ',
          'Having Issues?': 'મૂશ્કેલી આવી રહી છે?',
          '\nDon’t Worry,We got you!': '\nચિંતિત ના થાઓ, અમે આપની સાથે છીએ!',
          'Register Complaint': 'ફરિયાદ નોંધાવો',
          'View Complaints': 'ફરિયાદો જુઓ',
          'For further Assistance \nContact us at +910101010 ':
              'વધુ મદદ માટે\nઅમારો સંપર્ક કરો +910101010 પર',
          'Please fill the form below to register you complaint.':
              'કૃપા કરીને નીચેના ફોર્મમાં તમારી ફરિયાદ નોંધાવો.',
          'Problem': 'સમस्या',
          'Issue 1': 'મુદ્દો 1',
          'Describe your problem...': 'તમારી સમસ્યા વર્ણવો...',
          'HOME': 'મુખ્ય પાનું',
          'SEARCH': 'શોધો',
          'MAP': 'નકશો',
          'PROFILE': 'પ્રોફાઇલ',
          '* Required Fields': 'જરૂરી ફીલ્ડ્સ',
          'My Devices': 'મારા ઉપકરણો',
          'Add Device': 'ઉપકરણ ઉમેરો',
          'Name': 'નામ',
          'Created On': 'બનાવેલ તારીખ',
          'Dashboard': 'ડેશબોર્ડ',
          'Schedules': 'સમયસરણી',
          '< Back': '< પાછા',
          'Reload': 'ફરીથી લોડ કરો',
          'Additional Information....': 'વધુ માહિતી....',
          'Next': 'આગળ',
          'Add Note': 'નોંધ ઉમેરો',
          'Select IMEI': 'IMEI પસંદ કરો',
          'Select Device Title': 'ડિવાઈસ શીર્ષક પસંદ કરો',
          'Select Issue': 'મુદ્દો પસંદ કરો',
          'Please Fill Out The Form To Register Your Complaint':
              'કૃપા કરીને તમારું ફરિયાદ નોંધાવવા માટે ફોર્મ ભરો',
          'Note': 'નોંધ',
          'SUBMIT': 'સબમિટ કરો',
          'EDIT': 'સંપાદિત કરો',
          'Are all the details correct?': 'તમામ વિગતો બરાબર છે?',
          'Click Submit to confirm.': 'પુષ્ટિ કરવા માટે સબમિટ કરો',
          'Complaint Details': 'ફરિયાદ વિગતો',
          'Compliant': 'અનુકૂળ',
          'Programming': 'પ્રોગ્રામિંગ',
          'Logout': 'લૉગ આઉટ',
          'Edit Profile': 'પ્રોફાઇલ સંપાદિત કરો',
          'User Name': 'વપરાશકર્તાનું નામ',
          'Save': 'સાચવો',
          'Change Password': 'પાસવર્ડ બદલો',
          'Pending': 'અપુરું',
          'Ticket No': 'ટિકિટ નં',
          'Date': 'તારીખ',
          'Status': 'સ્થિતિ',
          'Expansion Mode': 'વિસ્તૃતિ મોડ',
          'Address': 'સરનામું',
          'Total valve Count': 'કુલ વાલ્વ ગણતરી',
          'Connected': 'કનેક્ટ કરેલ',
          'Not Connected': 'કનેક્ટ કરેલ નથી',
          'Device ID*': 'ડિવાઈસ ID*',
          'Device Name*': 'ડિવાઈસ નામ*',
          'DASHBOARD': 'ડેશબોર્ડ',
          'Settings': 'સેટિંગ્સ',
          'Delete Device': 'ડિવાઈસ કાઢી નાખો',
          'Update Device': 'ડિવાઈસ અપડેટ કરો',
          'Cancel': 'રદ કરો',
          'Program A': 'પ્રોગ્રામ A',
          'Program B': 'પ્રોગ્રામ B',
          'View': 'જુઓ',
          'SET': 'સેટ કરો',
          'Program': 'પ્રોગ્રામ',
          'Action': 'ક્રિયા',
          'My Programs': 'મારા પ્રોગ્રામ્સ',
          'Configure': 'કન્ફિગર કરો',
          'Create Program': 'પ્રોગ્રામ બનાવો',
          'Please Select the program and mode to create schedule':
              'કૃપા કરીને સમયસરણી બનાવવા માટે પ્રોગ્રામ અને મોડ પસંદ કરો',
          'Select Days': 'દિવસો પસંદ કરો',
          'Reset All': 'સૌ કોઈ રિસેટ કરો',
          'to follow the schedule': 'સમયસરણી અનુસરો',
          'Mode': 'મોડ',
          'Monday': 'સોમવાર',
          'Tuesday': 'મંગળવાર',
          'Wednesday': 'બુધવાર',
          'Thrusday': 'ગુરૂવાર',
          'Friday': 'શુક્રવાર',
          'Saturday': 'શનિવાર',
          'Sunday': 'રવિવાર',
          'Irrigation': 'સિંચાઇ',
          'Fertigation': 'ખેડાણ',
          'Start Time: ': 'પ્રારંભ સમય: ',
          'Valve Duration  : ': 'વાલ્વ સમયગાળો: ',
          'End Time  : ': 'સમાપ્તિ સમય: ',
          'Start Time 2 : ': 'પ્રારંભ સમય 2 : ',
          'Time exceeds 24 hours': 'સમય 24 કલાકથી વધારે છે',
          'Confirm': 'પુષ્ટિ કરો',
          'Start from today?': 'આજથી શરૂ કરશો?',
          'Pump initial time': 'પમ્પ પ્રારંભિક સમય',
          'Pump recharge time': 'પમ્પ રિચાર્જ સમય',
          'Days': 'દિવસો',
          'Power On': 'શક્તિ ચાલુ',
          'Power off': 'શક્તિ બંધ',
          'No Rain': 'વરસાદ નથી',
          'Raining': 'વરસાદ થઈ રહ્યો છે',
          'Low Flow': 'ઓછું પ્રવાહ',
          'Please fill the form below to edit you device.\nAdd all the required details':
              'તમારું ડિવાઈસ સંપાદિત કરવા માટે ફોર્મ ભરો.\nબધી જરૂરી વિગતો ઉમેરો'
        },
        "kn_IN": {
          'User Registration': 'ಬಳಕೆದಾರರ ನೋಂದಣಿ',
          'Name*': 'ಹೆಸರು',
          'Phone Number*': 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
          'Email ID*': 'ಇಮೇಲ್ ID',
          'Password*': 'ಪಾಸ್ವರ್ಡ್',
          'Confirm Password*': 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
          'Agree to Terms and Conditions': 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಒಪ್ಪಿ',
          'Register': 'ನೋಂದಣಿ',
          'Auto Detect GPS': 'ಸ್ವಯಂ ಜಿಪಿಎಸ್ ಪತ್ತೆ',
          'Country*': 'ದೇಶ',
          'State*': 'ರಾಜ್ಯ',
          'Pincode*': 'ಪಿನ್ ಕೋಡ್',
          'City*': 'ನಗರ',
          'Create': 'ರಚಿಸಿ',
          'Full Address': 'ಸಂಪೂರ್ಣ ವಿಳಾಸ',
          "Don't have an Account?": 'ಖಾತೆ ಇಲ್ಲವೇ?',
          'Almost there!': 'ಅರ್ಧ ಹೆಜ್ಜೆ ಉಳಿದಿದೆ!',
          'We have sent you an OTP\non number XXXXXX0000':
              'ನಾವು XXXXXX0000 ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಿದ್ದೇವೆ',
          'One time Password': 'ಒಂದು ಬಾರಿ ಪಾಸ್ವರ್ಡ್',
          'Didnt receive OTP?': 'OTP ಬಂದಿಲ್ಲವೇ?',
          'Resend SMS': 'SMS ಪುನಃ ಕಳುಹಿಸಿ',
          'Verify OTP': 'OTP ಪರಿಶೀಲಿಸಿ',
          'LOGIN': 'ಲಾಗಿನ್',
          "Don't have a Account": 'ಖಾತೆ ಇಲ್ಲವೇ',
          'via Email': 'ಇಮೇಲ್ ಮೂಲಕ',
          'via Phone': 'ಫೋನ್ ಮೂಲಕ',
          'Send OTP': 'OTP ಕಳುಹಿಸಿ',
          "Already have an account?": 'ಈಗಾಗಲೇ ಖಾತೆ ಇದ್ದೇ?',
          'OTP': 'OTP',
          'Login': 'ಲಾಗಿನ್',
          'Register Device': 'ಡಿವೈಸ್ ನೋಂದಣಿ',
          'Device Details': 'ಡಿವೈಸ್ ವಿವರಗಳು',
          'Device IMEI': 'ಡಿವೈಸ್ IMEI',
          'Device ID': 'ಡಿವೈಸ್ ID',
          'Device Name': 'ಡಿವೈಸ್ ಹೆಸರು',
          'GPS Location': 'ಜಿಪಿಎಸ್ ಸ್ಥಳ',
          'Current Location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
          'Supported Protocol': 'ಬೆಂಬಲಿತ ಪ್ರೋಟೋಕಾಲ್',
          'MQTT': 'MQTT',
          'Submit': 'ಸಲ್ಲಿಸು',
          'My Complaints': 'ನನ್ನ ದೂರಗಳು',
          'Complaint': 'ದೂರು',
          'Having Issues?': 'ಸಮಸ್ಯೆಗಳಾಗುತ್ತಿವೆ?',
          '\nDon’t Worry,We got you!': '\nಚಿಂತೆ ಬೇಡ, ನಾವು ನಿಮ್ಮೊಂದಿಗೆ ಇದ್ದೇವೆ!',
          'Register Complaint': 'ದೂರು ನೋಂದಣಿ',
          'View Complaints': 'ದೂರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
          'For further Assistance \nContact us at +910101010 ':
              'ಹೆಚ್ಚಿನ ನೆರವುಗಾಗಿ\n+910101010 ಸಂಪರ್ಕಿಸಿ',
          'Please fill the form below to register you complaint.':
              'ನಿಮ್ಮ ದೂರು ನೋಂದಣಿಗಾಗಿ ಈ ಫಾರ್ಮ್ ಅನ್ನು ಭರ್ತಿಮಾಡಿ',
          'Problem': 'ಸಮಸ್ಯೆ',
          'Issue 1': 'ವಿಷಯ 1',
          'Describe your problem...': 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ...',
          'HOME': 'ಮುಖಪುಟ',
          'SEARCH': 'ಹುಡುಕು',
          'MAP': 'ನಕ್ಷೆ',
          'PROFILE': 'ಪ್ರೊಫೈಲ್',
          '* Required Fields': 'ಅಗತ್ಯವಿರುವ ಕ್ಷೇತ್ರಗಳು',
          'My Devices': 'ನನ್ನ ಸಾಧನಗಳು',
          'Add Device': 'ಸಾಧನವನ್ನು ಸೇರಿಸಿ',
          'Name': 'ಹೆಸರು',
          'Created On': 'ತಯಾರಿಸಿದ ದಿನಾಂಕ',
          'Dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
          'Schedules': 'ವೇಳಾಪಟ್ಟಿ',
          '< Back': '< ಹಿಂದಕ್ಕೆ',
          'Reload': 'ಮರುಲೋಡ್',
          'Additional Information....': 'ಹೆಚ್ಚಿನ ಮಾಹಿತಿ....',
          'Next': 'ಮುಂದೆ',
          'Add Note': 'ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ',
          'Select IMEI': 'IMEI ಆಯ್ಕೆಮಾಡಿ',
          'Select Device Title': 'ಸಾಧನ ಶೀರ್ಷಿಕೆ ಆಯ್ಕೆಮಾಡಿ',
          'Select Issue': 'ವಿಷಯ ಆಯ್ಕೆಮಾಡಿ',
          'Please Fill Out The Form To Register Your Complaint':
              'ದೂರು ನೋಂದಣಿಗಾಗಿ ಫಾರ್ಮ್ ಭರ್ತಿಮಾಡಿ',
          'Note': 'ಟಿಪ್ಪಣಿ',
          'SUBMIT': 'ಸಲ್ಲಿಸು',
          'EDIT': 'ಸಂಪಾದಿಸಿ',
          'Are all the details correct?': 'ಎಲ್ಲಾ ವಿವರಗಳು ಸರಿಯೇ?',
          'Click Submit to confirm.': 'ದೃಢೀಕರಿಸಲು ಸಲ್ಲಿಸಿ ಕ್ಲಿಕ್ ಮಾಡಿ',
          'Complaint Details': 'ದೂರು ವಿವರಗಳು',
          'Compliant': 'ಅನುಗುಣ',
          'Programming': 'ಕಾರ್ಯಕ್ರಮ',
          'Logout': 'ಲಾಗ್ಔಟ್',
          'Edit Profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
          'User Name': 'ಬಳಕೆದಾರ ಹೆಸರು',
          'Save': 'ಉಳಿಸಿ',
          'Change Password': 'ಪಾಸ್ವರ್ಡ್ ಬದಲಿಸಿ',
          'Pending': 'ಬಾಕಿ',
          'Ticket No': 'ಟಿಕೆಟ್ ಸಂಖ್ಯೆ',
          'Date': 'ದಿನಾಂಕ',
          'Status': 'ಸ್ಥಿತಿ',
          'Expansion Mode': 'ವಿಸ್ತರಣೆ ಮೋಡ್',
          'Address': 'ವಿಳಾಸ',
          'Total valve Count': 'ಒಟ್ಟು ವಾಲ್ವ್ ಎಣಿಕೆ',
          'Connected': 'ಸಂಪರ್ಕಿಸಲಾಗಿದೆ',
          'Not Connected': 'ಸಂಪರ್ಕವಿಲ್ಲ',
          'Device ID*': 'ಸಾಧನ ID*',
          'Device Name*': 'ಸಾಧನ ಹೆಸರು*',
          'DASHBOARD': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
          'Settings': 'ಸಂಯೋಜನೆಗಳು',
          'Delete Device': 'ಸಾಧನವನ್ನು ಅಳಿಸಿ',
          'Update Device': 'ಸಾಧನವನ್ನು ನವೀಕರಿಸಿ',
          'Cancel': 'ರದ್ದುಮಾಡಿ',
          'Program A': 'ಕಾರ್ಯಕ್ರಮ A',
          'Program B': 'ಕಾರ್ಯಕ್ರಮ B',
          'View': 'ವೀಕ್ಷಿಸಿ',
          'SET': 'ಸೆಟ್',
          'Program': 'ಕಾರ್ಯಕ್ರಮ',
          'Action': 'ಕ್ರಿಯೆ',
          'My Programs': 'ನನ್ನ ಕಾರ್ಯಕ್ರಮಗಳು',
          'Configure': 'ಸಂರಚಿಸಿ',
          'Create Program': 'ಕಾರ್ಯಕ್ರಮ ರಚಿಸಿ',
          'Please Select the program and mode to create schedule':
              'ವೇಳಾಪಟ್ಟಿ ರಚಿಸಲು ಕಾರ್ಯಕ್ರಮ ಮತ್ತು ಮೋಡ್ ಆಯ್ಕೆಮಾಡಿ',
          'Select Days': 'ದಿನಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
          'Reset All': 'ಎಲ್ಲವನ್ನು ಮರುಹೊಂದಿಸಿ',
          'to follow the schedule': 'ವೇಳಾಪಟ್ಟಿ ಅನುಸರಿಸಲು',
          'Mode': 'ಮೋಡ್',
          'Monday': 'ಸೋಮವಾರ',
          'Tuesday': 'ಮಂಗಳವಾರ',
          'Wednesday': 'ಬುಧವಾರ',
          'Thrusday': 'ಗುರುವಾರ',
          'Friday': 'ಶುಕ್ರವಾರ',
          'Saturday': 'ಶನಿವಾರ',
          'Sunday': 'ಭಾನುವಾರ',
          'Irrigation': 'ನೀರಾವರಿ',
          'Fertigation': 'ರಸಗೊಬ್ಬರ ಬಳಕೆ',
          'Start Time: ': 'ಪ್ರಾರಂಭ ಸಮಯ:',
          'Valve Duration  : ': 'ವಾಲ್ವ್ ಅವಧಿ:',
          'End Time  : ': 'ಕೊನೆಯ ಸಮಯ:',
          'Start Time 2 : ': 'ಪ್ರಾರಂಭ ಸಮಯ 2:',
          'Time exceeds 24 hours': 'ಸಮಯವು 24 ಗಂಟೆಗಳನ್ನು ಮೀರುತ್ತದೆ',
          'Confirm': 'ದೃಢೀಕರಿಸಿ',
          'Start from today?': 'ಇಂದಿನಿಂದ ಪ್ರಾರಂಭಿಸಬಹುದೇ?',
          'Pump initial time': 'ಪಂಪ್ ಪ್ರಾರಂಭಿಕ ಸಮಯ',
          'Pump recharge time': 'ಪಂಪ್ ಮರುತುಂಬುವ ಸಮಯ',
          'Days': 'ದಿನಗಳು',
          'Power On': 'ವಿದ್ಯುತ್ ಚಾಲಿತ',
          'Power off': 'ವಿದ್ಯುತ್ ಬಿಗ್',
          'No Rain': 'ಮಳೆಯಿಲ್ಲ',
          'Raining': 'ಮಳೆ ಬೀಳುತ್ತಿದೆ',
          'Low Flow': 'ಕಡಿಮೆ ಹರಿವು',
          'Please fill the form below to edit you device.\nAdd all the required details':
              'ನಿಮ್ಮ ಸಾಧನವನ್ನು ಸಂಪಾದಿಸಲು ಫಾರ್ಮ್ ಭರ್ತಿಮಾಡಿ.\nಅಗತ್ಯವಿರುವ ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ'
        },
        "ta_IN": {
          'User Registration': 'பயனர் பதிவு',
          'Name*': 'பெயர்',
          'Phone Number*': 'தொலைபேசி எண்',
          'Email ID*': 'மின்னஞ்சல் ஐடி',
          'Password*': 'கடவுச்சொல்',
          'Confirm Password*': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
          'Agree to Terms and Conditions': 'நிபந்தனைகளை ஒப்புக்கொள்ளவும்',
          'Register': 'பதிவு செய்யவும்',
          'Auto Detect GPS': 'தன்னியக்க GPS அடையாளம்',
          'Country*': 'நாடு',
          'State*': 'மாவட்டம்',
          'Pincode*': 'பின் குறியீடு',
          'City*': 'நகரம்',
          'Create': 'தயாரிக்கவும்',
          'Full Address': 'முழு முகவரி',
          "Don't have an Account?": 'கணக்கென்று இல்லையா?',
          'Almost there!': 'தொடர்ந்து வருகிறேன்!',
          'We have sent you an OTP\non number XXXXXX0000':
              'நாங்கள் XXXXXX0000 எண்ணிற்கு OTP அனுப்பியுள்ளோம்',
          'One time Password': 'ஒரே முறை கடவுச்சொல்',
          'Didnt receive OTP?': 'OTP பெறவில்லை?',
          'Resend SMS': 'SMS-ஐ மறுதரிக்கவும்',
          'Verify OTP': 'OTP ஐ சரிபார்க்கவும்',
          'LOGIN': 'உள்நுழையவும்',
          "Don't have a Account": 'கணக்கு இல்லை',
          'via Email': 'மின்னஞ்சல் மூலம்',
          'via Phone': 'தொலைபேசி மூலம்',
          'Send OTP': 'OTP-ஐ அனுப்பவும்',
          "Already have an account?": 'ஏற்கனவே கணக்கு உள்ளதா?',
          'OTP': 'OTP',
          'Login': 'உள்நுழையவும்',
          'Register Device': 'தொகுப்புக் கணக்கைப் பதிவு செய்யவும்',
          'Device Details': 'தொகுப்புப் பக்கம்',
          'Device IMEI': 'தொகுப்புக் IMEI',
          'Device ID': 'தொகுப்புப் ID',
          'Device Name': 'தொகுப்புப் பெயர்',
          'GPS Location': 'GPS இடம்',
          'Current Location': 'தற்போதைய இடம்',
          'Supported Protocol': 'ஆதரிக்கப்படும் ஒழுங்கமைப்புகள்',
          'MQTT': 'MQTT',
          'Submit': 'சமர்ப்பிக்கவும்',
          'My Complaints': 'என் புகார்கள்',
          'Complaint': 'புகாரா',
          'Having Issues?': 'சிக்கல்கள் உள்ளதா?',
          '\nDon’t Worry,We got you!':
              '\nகண்டிப்பாக, நாங்கள் உங்களைப் பிடிக்கிறோம்!',
          'Register Complaint': 'புகாரை பதிவு செய்யவும்',
          'View Complaints': 'புகார்களைப் பார்க்கவும்',
          'For further Assistance \nContact us at +910101010 ':
              'மேலும் உதவிக்கான\மொழிபெயர்ப்பு: +910101010 உடன் தொடர்புகொள்ளவும்',
          'Please fill the form below to register you complaint.':
              'உங்கள் புகாரை பதிவு செய்ய கீழே உள்ள படிவத்தை பூர்த்தி செய்யவும்',
          'Problem': 'சிக்கல்',
          'Issue 1': 'முட்டை 1',
          'Describe your problem...': 'உங்கள் சிக்கலை விவரிக்கவும்...',
          'HOME': 'முகப்பக்கம்',
          'SEARCH': 'தேடல்',
          'MAP': 'நட்சம்',
          'PROFILE': 'சுயவிவர',
          '* Required Fields': 'தேவையான பகுதிகள்',
          'My Devices': 'என் சாதனங்கள்',
          'Add Device': 'சாதனத்தைச் சேர்க்கவும்',
          'Name': 'பெயர்',
          'Created On': 'தயாரிக்கப்பட்ட தேதி',
          'Dashboard': 'டாஷ்‌போர்ட்',
          'Schedules': 'அட்டவணைகள்',
          '< Back': '< திரும்ப',
          'Reload': 'மறுதொடக்கம்',
          'Additional Information....': 'கூடுதல் தகவல்....',
          'Next': 'அடுத்தது',
          'Add Note': 'குறிப்பு சேர்க்கவும்',
          'Select IMEI': 'IMEI தேர்வு செய்யவும்',
          'Select Device Title': 'சாதனத் தலைப்பைத் தேர்வு செய்யவும்',
          'Select Issue': 'முட்டையைத் தேர்வு செய்யவும்',
          'Please Fill Out The Form To Register Your Complaint':
              'உங்கள் புகாரை பதிவு செய்ய படிவத்தை நிரப்பவும்',
          'Note': 'குறிப்பு',
          'SUBMIT': 'சமர்ப்பிக்கவும்',
          'EDIT': 'திருத்து',
          'Are all the details correct?': 'அனைத்து விவரங்களும் சரிதானா?',
          'Click Submit to confirm.':
              'உறுதிப்படுத்த சமர்ப்பிக்கவும் கிளிக் செய்யவும்',
          'Complaint Details': 'புகாரின் விவரங்கள்',
          'Compliant': 'சரியானது',
          'Programming': 'பிரோகிராமிங்',
          'Logout': 'வெளியேறு',
          'Edit Profile': 'சுயவிவரத்தைத் திருத்தவும்',
          'User Name': 'பயனர் பெயர்',
          'Save': 'சேமிக்கவும்',
          'Change Password': 'கடவுச்சொல்லை மாற்றவும்',
          'Pending': 'நிலுவையில்',
          'Ticket No': 'டிக்கெட் எண்',
          'Date': 'தேதி',
          'Status': 'நிலையை',
          'Expansion Mode': 'விரிவாக்க முறை',
          'Address': 'முகவரி',
          'Total valve Count': 'மொத்த வால்வ் எண்ணிக்கை',
          'Connected': 'இணைக்கப்பட்டுள்ளது',
          'Not Connected': 'இணைக்கப்படவில்லை',
          'Device ID*': 'சாதன ID*',
          'Device Name*': 'சாதனத்தின் பெயர்*',
          'DASHBOARD': 'டாஷ்‌போர்ட்',
          'Settings': 'அமைப்புகள்',
          'Delete Device': 'சாதனத்தை அழிக்கவும்',
          'Update Device': 'சாதனத்தைப் புதுப்பிக்கவும்',
          'Cancel': 'ரத்து செய்',
          'Program A': 'பிரோகிராம் A',
          'Program B': 'பிரோகிராம் B',
          'View': 'காண்க',
          'SET': 'அமை',
          'Program': 'பிரோகிராம்',
          'Action': 'செயல்',
          'My Programs': 'என் நிரல்கள்',
          'Configure': 'அமை',
          'Create Program': 'பிரோகிராம் உருவாக்கவும்',
          'Please Select the program and mode to create schedule':
              'அட்டவணை உருவாக்கப் போகும் பிரோகிராம் மற்றும் முறைப் பொருத்தங்களைத் தேர்ந்தெடுக்கவும்',
          'Select Days': 'தினங்களைத் தேர்ந்தெடுக்கவும்',
          'Reset All': 'அனைத்தையும் மீட்டமைக்கவும்',
          'to follow the schedule': 'அட்டவணையைப் பின்பற்ற',
          'Mode': 'முறை',
          'Monday': 'திங்கட்கிழமை',
          'Tuesday': 'செவ்வாய்க்கிழமை',
          'Wednesday': 'புதன்கிழமை',
          'Thrusday': 'வியாழக்கிழமை',
          'Friday': 'வெள்ளிக்கிழமை',
          'Saturday': 'சனிக்கிழமை',
          'Sunday': 'ஞாயிற்றுக்கிழமை',
          'Irrigation': 'நீராவரி',
          'Fertigation': 'உழவியல்',
          'Start Time: ': 'துவக்கம் நேரம்: ',
          'Valve Duration  : ': 'வால்வ் காலம்: ',
          'End Time  : ': 'முடிவு நேரம்: ',
          'Start Time 2 : ': 'துவக்கம் நேரம் 2 : ',
          'Time exceeds 24 hours': 'நேரம் 24 மணிக்கூடுதலாக',
          'Confirm': 'உறுதிப்படுத்தவும்',
          'Start from today?': 'இன்று இருந்து தொடங்கவா?',
          'Pump initial time': 'பம்பின் ஆரம்ப காலம்',
          'Pump recharge time': 'பம்ப் ரீசார்ஜ் காலம்',
          'Days': 'நாட்கள்',
          'Power On': 'சக்தி இயக்கு',
          'Power off': 'சக்தி நிறுத்து',
          'No Rain': 'மழை இல்லை',
          'Raining': 'மழை பெய்கிறது',
          'Low Flow': 'குறைந்த ஓட்டம்',
          'Please fill the form below to edit you device.\nAdd all the required details':
              'உங்கள் சாதனத்தைத் திருத்த கீழே உள்ள படிவத்தை பூர்த்தி செய்யவும்.\nஅனைத்து தேவையான விவரங்களைச் சேர்க்கவும்'
        },
        "te_IN": {
          'User Registration': 'ఉపయోగकर्ता నమోదు',
          'Name*': 'పేరు',
          'Phone Number*': 'ఫోన్ నెంబర్',
          'Email ID*': 'ఈమెయిల్ ఐడి',
          'Password*': 'పాస్వర్డ్',
          'Confirm Password*': 'పాస్వర్డ్ నిర్ధారించండి',
          'Agree to Terms and Conditions': 'నిబంధనలు అంగీకరించండి',
          'Register': 'నమోదు చేయండి',
          'Auto Detect GPS': 'ఆటో డిటెక్ట్ GPS',
          'Country*': 'దేశం',
          'State*': 'రాష్ట్రం',
          'Pincode*': 'పిన్ కోడ్',
          'City*': 'నగరం',
          'Create': 'సృష్టించండి',
          'Full Address': 'మొత్తం చిరునామా',
          "Don't have an Account?": 'ఖాతా లేదు?',
          'Almost there!': 'ఇందుకు దగ్గరగా!',
          'We have sent you an OTP\non number XXXXXX0000':
              'మేము XXXXXX0000 నంబర్‌కు OTP పంపించాము',
          'One time Password': 'ఒకసారి పాస్వర్డ్',
          'Didnt receive OTP?': 'OTP రాలేదా?',
          'Resend SMS': 'SMS మళ్ళీ పంపించండి',
          'Verify OTP': 'OTP ధృవీకరించండి',
          'LOGIN': 'లాగిన్',
          "Don't have a Account": 'ఖాతా లేదు',
          'via Email': 'ఈమెయిల్ ద్వారా',
          'via Phone': 'ఫోన్ ద్వారా',
          'Send OTP': 'OTP పంపించండి',
          "Already have an account?": 'ఇప్పటికే ఖాతా ఉందా?',
          'OTP': 'OTP',
          'Login': 'లాగిన్',
          'Register Device': 'సాధనాన్ని నమోదు చేయండి',
          'Device Details': 'సాధన వివరాలు',
          'Device IMEI': 'సాధన IMEI',
          'Device ID': 'సాధన ID',
          'Device Name': 'సాధన పేరు',
          'GPS Location': 'GPS స్థానం',
          'Current Location': 'ప్రస్తుతం స్థానం',
          'Supported Protocol': 'మద్దతు ఇవ్వబడిన ప్రోటోకాల్',
          'MQTT': 'MQTT',
          'Submit': 'సమర్పించు',
          'My Complaints': 'నా ఫిర్యాదులు',
          'Complaint': 'ఫిర్యాదు',
          'Having Issues?': 'సమస్యలు కలవడం?',
          '\nDon’t Worry,We got you!': '\nచింతించకండి, మేము మీతో ఉన్నాము!',
          'Register Complaint': 'ఫిర్యాదు నమోదు చేయండి',
          'View Complaints': 'ఫిర్యాదులను వీక్షించండి',
          'For further Assistance \nContact us at +910101010 ':
              'ఇతర సహాయం కోసం\n+910101010 నంబర్‌కి సంప్రదించండి',
          'Please fill the form below to register you complaint.':
              'మీ ఫిర్యాదు నమోదు చేసేందుకు దిగువ ఫార్మ్‌ని నింపండి',
          'Problem': 'సమస్య',
          'Issue 1': 'ఇష్యూ 1',
          'Describe your problem...': 'మీ సమస్యను వివరణ ఇవ్వండి...',
          'HOME': 'హోమ్',
          'SEARCH': 'శోధన',
          'MAP': 'మాపు',
          'PROFILE': 'ప్రొఫైల్',
          '* Required Fields': 'అవసరమైన క్షేత్రాలు',
          'My Devices': 'నా పరికరాలు',
          'Add Device': 'పరికరాన్ని జోడించండి',
          'Name': 'పేరు',
          'Created On': 'సృష్టించబడింది',
          'Dashboard': 'డాష్‌బోర్డ్',
          'Schedules': 'షెడ్యూల్స్',
          '< Back': '< వెనుక',
          'Reload': 'మరలలోడ్',
          'Additional Information....': 'అదనపు సమాచారం....',
          'Next': 'తదుపరి',
          'Add Note': 'గమనిక జోడించండి',
          'Select IMEI': 'IMEI ఎంచుకోండి',
          'Select Device Title': 'పరికర శీర్షికను ఎంచుకోండి',
          'Select Issue': 'ఇష్యూ ఎంచుకోండి',
          'Please Fill Out The Form To Register Your Complaint':
              'మీ ఫిర్యాదు నమోదు చేయడానికి ఫార్మ్ నింపండి',
          'Note': 'గమనిక',
          'SUBMIT': 'సమర్పించు',
          'EDIT': 'సవరించు',
          'Are all the details correct?': 'అన్ని వివరాలు సరిగా ఉన్నాయా?',
          'Click Submit to confirm.': 'ధృవీకరించడానికి సమర్పించు క్లిక్ చేయండి',
          'Complaint Details': 'ఫిర్యాదు వివరాలు',
          'Compliant': 'సరైనది',
          'Programming': 'ప్రోగ్రామింగ్',
          'Logout': 'లాగౌట్',
          'Edit Profile': 'ప్రొఫైల్ సవరించండి',
          'User Name': 'వాడుకరి పేరు',
          'Save': 'సేవ్',
          'Change Password': 'పాస్వర్డ్ మారుస్తారు',
          'Pending': 'ప్రతిపాదించబడింది',
          'Ticket No': 'టికెట్ నం',
          'Date': 'తేదీ',
          'Status': 'స్థితి',
          'Expansion Mode': 'విస్రామ మోడ్',
          'Address': 'చిరునామా',
          'Total valve Count': 'మొత్తం వాల్వ్ లెక్క',
          'Connected': 'కనెక్ట్ చేయబడింది',
          'Not Connected': 'కనెక్ట్ చేయబడలేదు',
          'Device ID*': 'పరికర ID*',
          'Device Name*': 'పరికర పేరు*',
          'DASHBOARD': 'డాష్‌బోర్డ్',
          'Settings': 'అమరికలు',
          'Delete Device': 'పరికరాన్ని తీసివేయండి',
          'Update Device': 'పరికరాన్ని నవీకరించండి',
          'Cancel': 'రద్దు చేయండి',
          'Program A': 'ప్రోగ్రామ్ A',
          'Program B': 'ప్రోగ్రామ్ B',
          'View': 'చూడండి',
          'SET': 'సెట్',
          'Program': 'ప్రోగ్రామ్',
          'Action': 'చర్య',
          'My Programs': 'నా ప్రోగ్రామ్‌లు',
          'Configure': 'ఆకారాన్ని సర్దుబాటు చేయండి',
          'Create Program': 'ప్రోగ్రామ్ సృష్టించండి',
          'Please Select the program and mode to create schedule':
              'షెడ్యూల్ సృష్టించడానికి ప్రోగ్రామ్ మరియు మోడ్‌ని ఎంచుకోండి',
          'Select Days': 'రోజులను ఎంచుకోండి',
          'Reset All': 'అన్ని రీసెట్ చేయండి',
          'to follow the schedule': 'షెడ్యూల్‌ను అనుసరించడానికి',
          'Mode': 'మోడ్',
          'Monday': 'సోమవారం',
          'Tuesday': 'మంగళవారం',
          'Wednesday': 'బుధవారం',
          'Thrusday': 'గురువారం',
          'Friday': 'శుక్రవారం',
          'Saturday': 'శనివారం',
          'Sunday': 'ఆదివారం',
          'Irrigation': 'సరస్సు',
          'Fertigation': 'రసాయన రకాలవలపు',
          'Start Time: ': 'ప్రారంభ సమయం: ',
          'Valve Duration  : ': 'వాల్వ్ వ్యవధి : ',
          'End Time  : ': 'ముడివేత సమయం : ',
          'Start Time 2 : ': 'ప్రారంభ సమయం 2 : ',
          'Time exceeds 24 hours': 'సమయం 24 గంటలు దాటుతుంది',
          'Confirm': 'తొలగించు',
          'Start from today?': 'ఈ రోజు మొదలవుతుంది?',
          'Pump initial time': 'పంప్ ప్రారంభ సమయం',
          'Pump recharge time': 'పంప్ రీచార్జ్ సమయం',
          'Days': 'రోజులు',
          'Power On': 'పవర్ ఆన్',
          'Power off': 'పవర్ ఆఫ్',
          'No Rain': 'వర్షం లేదు',
          'Raining': 'వర్షం పడుతుంది',
          'Low Flow': 'తక్కువ ప్రవాహం',
          'Please fill the form below to edit you device.\nAdd all the required details':
              'మీ పరికరాన్ని సవరించడానికి దిగువ ఫార్మ్‌ను నింపండి.\nఅన్ని అవసరమైన వివరాలను జోడించండి'
        }
      };
}
